// 'use client';
import type { Metadata } from "next";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


import { Geist, Geist_Mono } from "next/font/google";
 import "./globals.css";

 import Navbar from './components/Navbar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * @constant metadata
 * @description Metadados da aplicação Next.js, incluindo título e descrição.
 * Estes metadados são usados para SEO e para a exibição no navegador.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * @component RootLayout
 * @description Componente de layout raiz da aplicação Next.js. Ele define a estrutura HTML básica,
 * importa fontes personalizadas, aplica estilos globais e inclui componentes como `Navbar`
 * e `SecurityMonitor` que são persistentes em todas as páginas.
 *
 * @param {Readonly<{ children: React.ReactNode }>} { children } As props children representam o conteúdo da página atual.
 * @returns {JSX.Element} O layout raiz da aplicação.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en">
       <body
         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
       >
         <Navbar />
         <div className="pt-16">
           {children}
         </div>

         <ToastContainer />
       </body>
     </html>
   );
 }
