services:
  - type: web
    name: backend
    env: python
    buildCommand: "poetry install && poetry build"
    preDeployCommand: "poetry run python app/initial_data.py"
    startCommand: "poetry run python -m app.initial_data && poetry run uvicorn app.main:app --host 0.0.0.0 --port 10000"